<html>
<head>
<meta charset='utf-8'>
<style>
.pass {
    font-weight: bold;
    color: green;
}
.fail {
    font-weight: bold;
    color: red;
}
</style>

<script>
if (window.testRunner)
    testRunner.dumpAsText();

function SputnikError(message)
{
    this.message = message;
}

SputnikError.prototype.toString = function ()
{
    return 'SputnikError: ' + this.message;
};

var sputnikException;

function testPrint(msg)
{
    var span = document.createElement("span");
    document.getElementById("console").appendChild(span); // insert it first so XHTML knows the namespace 
    span.innerHTML = msg + '<br />';
}

function escapeHTML(text)
{
    return text.toString().replace(/&/g, "&amp;").replace(/</g, "&lt;");
}

function printTestPassed(msg)
{
    testPrint('<span><span class="pass">PASS</span> ' + escapeHTML(msg) + '</span>');
}

function printTestFailed(msg)
{
    testPrint('<span><span class="fail">FAIL</span> ' + escapeHTML(msg) + '</span>');
}

function testFailed(msg)
{
    throw new SputnikError(msg);
}

var successfullyParsed = false;
</script>

</head>
<body>
<p>S14_D7</p>
<div id='console'></div>
<script>
try {

/**
* @name: S14_D7;
* @section: 14;
* @assertion: Function declaration may be inside of "with" block ;
*/

BANNER="union jack";

a=1;

//////////////////////////////////////////////////////////////////////////////
//CHECK#1
if (typeof __func !== "function") {
	testFailed('1: Function declaration may be inside of "with" block');
}
//
//////////////////////////////////////////////////////////////////////////////

__obj={a:2};

with(__obj){
    function __func(){return a;};
}

//////////////////////////////////////////////////////////////////////////////
//CHECK#2
if (__func() !== 1) {
	testFailed('2: Function declaration may be inside of "with" block ');
}
//
//////////////////////////////////////////////////////////////////////////////

__obj.a=BANNER;

with(__obj){
    //////////////////////////////////////////////////////////////////////////////
    //CHECK#3
    if (__func() !== "union jack") {
	   testFailed('3: Function declaration may be inside of "with" block ');
    }
    //
    ////////////////////////////////////////////////////////////////////////////// 
}



} catch (ex) {
    sputnikException = ex;
}

var successfullyParsed = true;
</script>

<script>
if (!successfullyParsed)
    printTestFailed('successfullyParsed is not set');
else if (sputnikException)
    printTestFailed(sputnikException);
else
    printTestPassed("");
testPrint('<br /><span class="pass">TEST COMPLETE</span>');
</script>
</body>
</html>
